apiVersion: v1
kind: Service 
metadata:
  name: adminer
spec:
  selector:
    app: adminer # Pilih pod dengan label app: adminer
  ports:
    - port: 8080       # Port yang akan diekspos oleh Service
      targetPort: 8080 # Port yang didengarkan oleh kontainer Adminer