apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: adminer
spec:
  to:
    kind: Service
    name: adminer # Ganti dengan nama service yang sesuai
  port:
    targetPort: 8080 # Ganti dengan port yang sesuai jika berbeda
  tls:
    termination: edge # Gunakan 'edge' untuk TLS termination di route
