name: Trigger OpenShift Build
on:
  push:
    branches:
      - master

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      
    - name: Send Telegram Notification
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🚨 Merge to Main Branch 🚨\nA merge commit has been made to the main branch. Please review the changes!"

    # - name: Install OC CLI
    #   run: |
    #     curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
    #     tar -xzf openshift-client-linux.tar.gz
    #     sudo mv oc kubectl /usr/local/bin/

    # - name: Login to OpenShift
    #   run: |
    #     oc login --token="${{secrets.OC_TOKEN}}" --server="${{secrets.OC_SERVER}}"

    # - name: Start OpenShift Build
    #   run: |
    #     oc start-build "${{secrets.OC_BUILD_NAME}}" -n "${{secrets.OC_NAMESPACE}}" --wait --follow
